### ISSUE TITLE
Compatibility with macOS

### ISSUE THREAD

**Issue by gwsounddsg** [RTTrP/RTTrP-v1.8.7.0#11]
Hi,

Currently in `C++/protocol_common.h` it uses `winsock2.h` which isn't compatible with macOS. Could there be an update to work with macOS? 

If I comment out that include, the only errors I get are in `thirdParty_motion.cpp` (lines: 384, 389, 394, 400, 404, 408) because it doesn't know what `M_PI` is. Simply adding `#include<cmath>` fixes that.

Thanks,
GW

**Comment by btmarty** [comment]
Hello GW,

Thanks for submitting this! As we don’t have a macOS environment, we won’t be able to test and confirm this change, but if you wanted to fork the repo, and submit a pull request, I can merge your changes into a new branch called ‘macOS’ with a disclaimer that this wasn’t tested by CAST.

Would that work for you?

Thanks!

Marty Cochrane
BlackTrax Product Manager

**Comment by gwsounddsg** [comment]
Great. Just did the pull request. Thanks!

**Comment by btmarty** [comment]
Perfect thanks! I’ll create a branch and do the merge when I get back to the office.

Thank you!

Marty Cochrane
BlackTrax Product Manager
