### ISSUE TITLE
Usage examples: how to implement package sender?

### ISSUE THREAD

**Issue by khssnv** [RTTrP/RTTrP-v1.8.7.0#2]
Hello. I'm trying to implement RTTrPM sender to control my RTTrPM software. I've found an example on how to use this package to implement a reader / decoder: https://github.com/CAST-Software/RTTrP-Reader, but seems like this implementation not suite for sender. As I see, there are no tools to encode my data in to RTTrPM standard. Wiki shows more then 10 examples of systems that works on RTTrPM, I'm sure you have a library or module for package sender. Can you publish it please? Usage examples could be handy as well.

Sure, there are specs at [wiki](https://rttrp.github.io/RTTrP-Wiki/RTTrPM.html) but it's painful to implement it in such a low level.

**Comment by marty0678** [comment]
We currently don't have any sending examples or applications that are publically available, unfortunately. My best suggestion would be to check out the packet specs as you have noted.

If this changes I'll update this thread, but will close it for now.
